[group:chartjot]
programs=chartjot-horizon

[program:chartjot-horizon]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/chartjot/current
command=/usr/bin/php artisan horizon
stdout_logfile=/var/log/supervisor/chartjot/horizon.log
redirect_stderr=true
logfile_maxbytes=40MB
logfile_backups=1
autostart=true
autorestart=true
user=ubuntu
numprocs=1
stopsignal=TERM
stopwaitsecs=300
stopasgroup=true
killasgroup=true
